# map configurations
[map]
    # compatible game-modes
    compatible_game_modes = [
        "sandbox",
        "vzombies"
    ]

    # list of spawn points
    spawn_points = [
        { location = "Vector(-328.000, 429.000, 20.000)", rotation = "Rotator(0.000000, 0.000000, 0.000000)" },
        { location = "Vector(-275.000, -392.000, 20.000)", rotation = "Rotator(0.000000, 0.000000, 0.000000)" },
        { location = "Vector(-244.000, 135.000, 20.000)", rotation = "Rotator(0.000000, 0.000000, 0.000000)" },
        { location = "Vector(-317.000, -96.000, 20.000)", rotation = "Rotator(0.000000, 0.000000, 0.000000)" },
    ]

[custom_data]
