# asset pack configurations
[asset_pack]
    # asset pack name
    name =              "zm-spiral"
    # contributors
    author =            "Voltaism"
    # version
    version =           "0.1.0"
    # image URL
    image =             "https://i.imgur.com/fKEyhB9.png"
    # unreal engine folder - the name of the root folder (the one inside UnrealProject/Content/) which the assets will have references to each other
    unreal_folder =     "zm-spiral"

# assets files
[assets]
    # maps
    [assets.maps]
        zm-spiral = "zm-spiral"

    # static meshes
    [assets.static_meshes]
        SM_Template_Map_Floor1 = "Meshes/SM_Template_Map_Floor1"
        SpiralCube = "Meshes/SpiralCube"

    # skeletal meshes
    [assets.skeletal_meshes]
        # SK_Better_Man = "Characters/SK_BetterMan_03"
        # ...

    # sounds
    [assets.sounds]
        # A_Awesome_Music = "Sounds/A_Awesome_Music"
        # ...

    # animations
    [assets.animations]
        # A_Character_Jump = "Animations/A_Character_Jump"
        # ...

    # particles
    [assets.particles]
        # P_Big_Explosion = "Particles/P_Big_Explosion"
        # ...

    # materials
    [assets.materials]
        # M_Red_Textured = "Materials/M_Red_Textured"
        # ...

    # other assets (for not yet categorized ones)
    [assets.others]
        # A_Audio_Rifle_Fire = "Audios/A_Audio_Rifle_Fire_03"
        # ...
